<a href="https://colab.research.google.com/github/yangliupku/cs336_assignment1_basics/blob/main/notebooks/assignment1_torch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import torch

def get_device(index: int = 0) -> torch.device:
    """Try to use the GPU if possible, otherwise, use CPU."""
    if torch.cuda.is_available():
        return torch.device(f"cuda:{index}")
    else:
        return torch.device("cpu")

get_device()

device(type='cpu')

# Tensors

In [34]:
x1 = torch.tensor([[1,2,3], [4,5,6]])
x1


torch.Size([2, 3])

In [37]:
x1.shape

torch.Size([2, 3])

In [38]:
x1.size()

torch.Size([2, 3])

In [39]:
x2 = torch.ones(x1.shape)
x2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [41]:
x3 = torch.zeros(5)
x3

tensor([0., 0., 0., 0., 0.])

In [44]:
x4 = torch.empty(5, device=get_device(), dtype=torch.bfloat16)
x4

tensor([-1.1990e+20,  8.5493e-10,  0.0000e+00,  0.0000e+00, -2.4425e-15],
       dtype=torch.bfloat16)

In [45]:
torch.nn.init.trunc_normal_(x4, mean=0, std=1, a=-3, b=3)

tensor([ 0.9570, -1.4609,  0.6094, -0.3184, -0.0195], dtype=torch.bfloat16)

In [46]:
x4

tensor([ 0.9570, -1.4609,  0.6094, -0.3184, -0.0195], dtype=torch.bfloat16)

# Linear Module

In [61]:
l = torch.nn.Linear(in_features=5, out_features=3, bias=True)

In [62]:
l.weight

Parameter containing:
tensor([[ 0.1643,  0.0457, -0.1929, -0.2275, -0.0756],
        [-0.0430, -0.1433,  0.1495,  0.0888, -0.4435],
        [-0.1962,  0.0072, -0.3657,  0.1534,  0.2723]], requires_grad=True)

In [63]:
l.bias

Parameter containing:
tensor([0.3559, 0.1255, 0.2927], requires_grad=True)

In [64]:
for p in l.parameters():
  print(p)

Parameter containing:
tensor([[ 0.1643,  0.0457, -0.1929, -0.2275, -0.0756],
        [-0.0430, -0.1433,  0.1495,  0.0888, -0.4435],
        [-0.1962,  0.0072, -0.3657,  0.1534,  0.2723]], requires_grad=True)
Parameter containing:
tensor([0.3559, 0.1255, 0.2927], requires_grad=True)


In [65]:
l.get_parameter('weight')

Parameter containing:
tensor([[ 0.1643,  0.0457, -0.1929, -0.2275, -0.0756],
        [-0.0430, -0.1433,  0.1495,  0.0888, -0.4435],
        [-0.1962,  0.0072, -0.3657,  0.1534,  0.2723]], requires_grad=True)

In [66]:
l.get_parameter('bias')

Parameter containing:
tensor([0.3559, 0.1255, 0.2927], requires_grad=True)

In [68]:
for p in l.named_parameters():
  print(p)

('weight', Parameter containing:
tensor([[ 0.1643,  0.0457, -0.1929, -0.2275, -0.0756],
        [-0.0430, -0.1433,  0.1495,  0.0888, -0.4435],
        [-0.1962,  0.0072, -0.3657,  0.1534,  0.2723]], requires_grad=True))
('bias', Parameter containing:
tensor([0.3559, 0.1255, 0.2927], requires_grad=True))


## state dict


In [69]:
l.state_dict()

OrderedDict([('weight',
              tensor([[ 0.1643,  0.0457, -0.1929, -0.2275, -0.0756],
                      [-0.0430, -0.1433,  0.1495,  0.0888, -0.4435],
                      [-0.1962,  0.0072, -0.3657,  0.1534,  0.2723]])),
             ('bias', tensor([0.3559, 0.1255, 0.2927]))])

In [70]:
torch.save(l.state_dict(), "test_1.pth")

In [71]:
d = torch.load("test_1.pth")

In [72]:
d

OrderedDict([('weight',
              tensor([[ 0.1643,  0.0457, -0.1929, -0.2275, -0.0756],
                      [-0.0430, -0.1433,  0.1495,  0.0888, -0.4435],
                      [-0.1962,  0.0072, -0.3657,  0.1534,  0.2723]])),
             ('bias', tensor([0.3559, 0.1255, 0.2927]))])

In [73]:
l2= torch.nn.Linear(in_features=5, out_features=3, bias=True)

In [74]:
l2.load_state_dict(d)

<All keys matched successfully>

In [79]:
## run module

In [76]:
x = torch.randn(5)

In [78]:
l(x)

tensor([ 0.0580, -0.0108, -0.2359], grad_fn=<ViewBackward0>)